------------------
-- Instructions --
------------------

-- This is a Lua file containing all the text in the game.
-- To translate the text in the game change the strings to their translated versions.
-- Some things to note is that since double quotes are needed to enclose the strings, they need to be escaped
-- if they are needed inside a string, by writing them as \" (see t[99] as an example).
--
-- The comments at the end of each line give some additional information about the text.
-- Text tagged as INES, PRESIDENT_INES, LEE, HOLEEGRAM, COLLECTOR, ANDREA, PAOLO, PEPPE is text that appears as spoken
-- dialogue, and the tag indicates which character is speaking.
-- PEPPE, PAOLO, and ANDREA are the three musicians in the sixties, from left to right.
-- Text tagged as LOOK appears only as the description of an object/hotspot when the cursor is above it.
-- Text tagged as ECHO appears as a dialogue option that is also spoken by the protagonist when selected.
-- Text tagged as NOECHO appears only as a dialogue option but is not spoken.
-- Text tagged as TEXT
--
-- If the language you are translating into does not use spaces between words you will need to break lines manually
-- inside the text that needs to wrap (text spoken by the characters, as well as LOOK and ECHO tags).
-- Line breaks are encoded as \n inside Lua strings. You can test how the text will be displayed with the provided online tester,
-- which can be found at https://sellaroli.com/apps/nem-translation-tool/
--
---------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------

local t = {}

t[1] = "Я не могу этого сделать."  -- {TEXT, input.moon}
t[2] = "Это точно не сработает"  -- {TEXT, input.moon}
t[3] = "Нее."  -- {TEXT, input.moon}
t[4] = "Возможно попозже."  -- {TEXT, input.moon}
t[5] = "настройки"  -- {TEXT, ui/cursor.moon}
t[6] = "Пустота. Кругом пустота."  -- {LOOK, rooms/present.moon}
t[7] = "окна"  -- {TEXT, rooms/present.moon}
t[8] = "Как минимум сейчас у него есть причина не смотреть на дорогу."  -- {LOOK, rooms/present.moon}
t[9] = "дядюшка Ли"  -- {TEXT, rooms/present.moon}
t[10] = "Готово. Вот."  -- {INES, rooms/present.moon}
t[11] = "Ну, удачи тебе, короче. Твой косяк, если не сработает."  -- {INES, rooms/present.moon}
t[12] = "Временной туннель? Нет уж, тут мне и дня не протянуть!"  -- {INES, rooms/present.moon}
t[357] = "Расслабься. Один щелчок и вот мы снова дома!"  -- {LEE, rooms/present.moon}
t[13] = "Вот же..."  -- {INES, rooms/present.moon}
t[14] = "Бесполезно. Это же та сломанная штука, которую он мне подсунул!"  -- {INES, rooms/present.moon}
t[15] = "Ну дядь Ли, ну зачем?"  -- {LOOK, rooms/present.moon}
t[16] = "хроно-катапульта"  -- {TEXT, rooms/present.moon}
t[17] = "Это похоже на какую-то звонилку."  -- {INES, rooms/present.moon}
t[18] = "Он сделал машину времени из звонилки?!"  -- {INES, rooms/present.moon}
t[19] = "Тут на \"быстрый набор\" какие-то времена записаны."  -- {INES, rooms/present.moon}
t[20] = "растение"  -- {TEXT, rooms/present.moon}
t[21] = "Опять дядя Ли со своими странными привычками. Растение в фургоне, серьёзно?"  -- {LOOK, rooms/present.moon}
t[22] = "Чую я, что в горшке этом что-то есть!"  -- {INES, rooms/present.moon}
t[23] = "Запасной девайс на всякий случай."  -- {INES, rooms/present.moon}
t[24] = "Как это туда попало?"  -- {INES, rooms/present.moon}
t[25] = "Вот эту штукенцию я недавно нашла прямо в этом горшке."  -- {INES, rooms/present.moon}
t[26] = "Я думаю в горшке этому девайсу уже не место"  -- {INES, rooms/present.moon}
t[27] = "Интуиция подсказывает, что я на правильном пути."  -- {INES, rooms/present.moon}
t[62] = "Она пялится на этот плакат так, как будто влюбилась в него."  -- {LOOK, rooms/collector.moon}
t[63] = "Она буквально сверлит меня взглядом."  -- {LOOK, rooms/collector.moon}
t[64] = "Она настолько внимательно слушает, что никак не может оторваться от этой демо записи."  -- {LOOK, rooms/collector.moon}
t[65] = "?"  -- {TEXT, rooms/collector.moon}
t[66] = "коллекционер"  -- {TEXT, rooms/collector.moon}
t[67] = "Угу."  -- {INES, rooms/collector.moon}
t[371] = "Это то..."  -- {COLLECTOR, rooms/collector.moon}
t[372] = "...это ведь то о чём я думаю?"  -- {COLLECTOR, rooms/collector.moon}
t[68] = "Ага."  -- {INES, rooms/collector.moon}
t[373] = "Настоящая находка!"  -- {COLLECTOR, rooms/collector.moon}
t[374] = "Ущипните меня, я не могу поверить в это!"  -- {COLLECTOR, rooms/collector.moon}
t[375] = "Мне нужно немедленно прослушать это, дабы развеять все сомнения."  -- {COLLECTOR, rooms/collector.moon}
t[376] = "Пожалуйста, держи руки при себе пока я в нирване."  -- {COLLECTOR, rooms/collector.moon}
t[69] = "Вот."  -- {INES, rooms/collector.moon}
t[377] = "Это что такое?"  -- {COLLECTOR, rooms/collector.moon}
t[70] = "Так это демо-кассета известной рок-группы, которая раньше владела этим ржавым фургончиком"  -- {INES, rooms/collector.moon}
t[71] = "Ты 100% горишь желанием, заполучить эту легендарную кассету"  -- {INES, rooms/collector.moon}
t[378] = "Это невероятно, кассета выглядит так, будто её записали прямо сегодня."  -- {COLLECTOR, rooms/collector.moon}
t[379] = "Ты реально думаешь, что я поверю в то, что она из 60-х?"  -- {COLLECTOR, rooms/collector.moon}
t[72] = "Да, это правда так! Клянусь всем, что у меня есть!"  -- {INES, rooms/collector.moon}
t[380] = "Красивая сказочка, \"гостья из будущего\", но меня так просто не провести.  -- {COLLECTOR, rooms/collector.moon}
t[381] = "Убирайся-ка отсюда, вместе со своим барахлом."  -- {COLLECTOR, rooms/collector.moon}
t[73] = "Пыталась убедить, что не подделка. Но не хочет верить, хоть тресни."  -- {INES, rooms/collector.moon}
t[74] = "Типо не выглядит так, будто вещь достаточно старая."  -- {INES, rooms/collector.moon}
t[75] = "Подозрительно."  -- {LOOK, rooms/collector.moon}
t[76] = "медиатор"  -- {TEXT, rooms/collector.moon}
t[77] = "Они в прямом смысле использовали медиатор во время создания этого постера."  -- {INES, rooms/collector.moon}
t[78] = "Ну да, конечно, ведь все же так делают."  -- {INES, rooms/collector.moon}
t[79] = "Композиция - это просто огонь! Все сделано для того, чтобы заметить этот медиатор."  -- {LOOK, rooms/collector.moon}
t[80] = "Гениально и опережает свое время. А точно ли это выглядело именно так?"  -- {LOOK, rooms/collector.moon}
t[81] = "постер"  -- {TEXT, rooms/collector.moon}
t[82] = "Хэй, а медиатор в руках гитариста уж какой-то подозрительный."  -- {INES, rooms/collector.moon}
t[83] = "Это походу то, что художники называют \"рельефом\"."  -- {INES, rooms/collector.moon}
t[84] = "Потрепанный жизнью, зато стильный кассетный диктофон красного цвета. Это мне надо."  -- {LOOK, rooms/collector.moon}
t[85] = "кассетный диктофон"  -- {TEXT, rooms/collector.moon}
t[382] = "Руки прочь!"  -- {COLLECTOR, rooms/collector.moon}
t[383] = "Эта вещь дороже всего на свете."  -- {COLLECTOR, rooms/collector.moon}
t[86] = "Черт возьми."  -- {INES, rooms/collector.moon}
t[87] = "Хе-хе."  -- {INES, rooms/collector.moon}
t[384] = "А, опять ты здесь."  -- {COLLECTOR, rooms/collector.moon}
t[385] = "ХЭЙ!"  -- {COLLECTOR, rooms/collector.moon}
t[386] = "Быстро проваливай отсюда!"  -- {COLLECTOR, rooms/collector.moon}
t[387] = "Обходи стороной мой шедевральный и великолепный постер."  -- {COLLECTOR, rooms/collector.moon}
t[88] = "растение"  -- {TEXT, rooms/collector.moon}
t[89] = "Неужели это такое же растение, что и в фургоне у дядюшки Ли? "  -- {LOOK, rooms/collector.moon}
t[90] = "Тааак..."  -- {INES, rooms/collector.moon}
t[91] = "...я нашла рабочий девайс, который бережно оставила для дяди Ли в горшке с растением."  -- {INES, rooms/collector.moon}
t[92] = "Который походу тот самый девайс, которым я сейчас пользуюсь."  -- {INES, rooms/collector.moon}
t[93] = "Значит, получается, во избежание временных аномалий, я должна оставить это прямо вот здесь, чтобы я из прошлого могла найти эту вещь в будущем. "  -- {INES, rooms/collector.moon}
t[94] = "Которое на самом деле так то настоящее."  -- {INES, rooms/collector.moon}
t[95] = "...ёмаё."  -- {INES, rooms/collector.moon}
t[96] = "От этих временных парадоксов мой МОЗГ просто ВЗРЫВАЕТСЯ."  -- {INES, rooms/collector.moon}
t[97] = "Поставлю значит эту штуковину обратно в горшок, а потом кнопку оттуда же и нажму."  -- {INES, rooms/collector.moon}
t[98] = "книги"  -- {TEXT, rooms/collector.moon}
t[99] = "И все они это копия одной и той же книги под названием: \"Группа, в которой нет барабанщика\"."  -- {LOOK, rooms/collector.moon}
t[100] = "диски"  -- {TEXT, rooms/collector.moon}
t[101] = "Они выглядят свежее, чем большая часть здешнего хлама."  -- {LOOK, rooms/collector.moon}
t[102] = "пластинки"  -- {TEXT, rooms/collector.moon}
t[103] = "Это же винил. Еще помню как их крутили, вот настолько я динозавр."  -- {LOOK, rooms/collector.moon}
t[104] = "магнитофон"  -- {TEXT, rooms/collector.moon}
t[105] = "Высокотехнологичный предмет. Как минимум таким он был пару десятков лет назад."  -- {LOOK, rooms/collector.moon}
t[28] = "Я не могу туда попасть, силовое поле мешает мне это сделать."  -- {INES, rooms/future.moon}
t[29] = "Единственное золото, которое можно повстречать в этой игре."  -- {LOOK, rooms/future.moon}
t[30] = "Выглядит очень знакомо. "  -- {LOOK, rooms/future.moon}
t[31] = "монетка"  -- {TEXT, rooms/future.moon}
t[32] = "Мне вдруг показалось, что золота в этой игре больше и нет!"  -- {INES, rooms/future.moon}
t[33] = "Аааа, она просто позолоченная."  -- {INES, rooms/future.moon}
t[34] = "Надеюсь, что это не обернется потом против меня."  -- {INES, rooms/future.moon}
t[35] = "Табличка с описанием монетки."  -- {LOOK, rooms/future.moon}
t[36] = "табличка"  -- {TEXT, rooms/future.moon}
t[37] = "Здесь сказано, что это реплика самой первой монетки, которую заработал дядя Ли."  -- {INES, rooms/future.moon}
t[38] = "И по ходу оригинал был утерян, когда я еще была ребенком."  -- {INES, rooms/future.moon}
t[39] = "Хе-хе."  -- {INES, rooms/future.moon}
t[40] = "Куда же он вляпался на этот раз?"  -- {LOOK, rooms/future.moon}
t[41] = "Каким-то образом он все еще продолжает удивлять меня."  -- {LOOK, rooms/future.moon}
t[42] = "дядя Ли?"  -- {TEXT, rooms/future.moon}
t[43] = "хулиграмма"  -- {TEXT, rooms/future.moon}
t[44] = "дядь Ли?"  -- {INES, rooms/future.moon}
t[45] = "Это силовое поле точно не позволяет ему меня услышать."  -- {INES, rooms/future.moon}
t[46] = "Пиксели всё портят, эх! Наверняка люк обалденный, прямо весь расписной."  -- {LOOK, rooms/future.moon}
t[47] = "открытие"  -- {TEXT, rooms/future.moon}
t[48] = "Я не могу сделать этого находясь здесь"  -- {INES, rooms/future.moon}
t[49] = "Вот тут одна из вещей, которые ты ищешь."  -- {INES, rooms/future.moon}
t[50] = "И вот тут еще одна штука, которая тебе нужна."  -- {INES, rooms/future.moon}
t[358] = "Вкусняшка!"  -- {HOLEEGRAM, rooms/future.moon}
t[51] = "...чего?"  -- {INES, rooms/future.moon}
t[359] = "Я молчу. Тебе показалось."  -- {HOLEEGRAM, rooms/future.moon}
t[52] = "Расслабься... Так ты можешь отремонтировать эту штуковину?"  -- {INES, rooms/future.moon}
t[360] = "Прям сейчас займусь этим."  -- {HOLEEGRAM, rooms/future.moon}
t[361] = "Биииип, Бооооп."  -- {HOLEEGRAM, rooms/future.moon}
t[362] = "Бджжжжььььь."  -- {HOLEEGRAM, rooms/future.moon}
t[363] = "Ну все, готово. Не стоит благодарностей."  -- {HOLEEGRAM, rooms/future.moon}
t[53] = "Почему мне следует это сделать?"  -- {INES, rooms/future.moon}
t[54] = "Сидят и не шелохнутся. Должно быть им не по себе."  -- {LOOK, rooms/past.moon}
t[55] = "музыкальная шпана"  -- {TEXT, rooms/past.moon}
t[56] = "Почему мне следует это сделать? "  -- {INES, rooms/past.moon}
t[57] = "Это же тот медиатор, который вы разыскиваете?"  -- {INES, rooms/past.moon}
t[364] = "Мой медиатор!"  -- {PEPPE, rooms/past.moon}
t[365] = "Мой любименький медиатор!"  -- {PEPPE, rooms/past.moon}
t[366] = "Мы так сильно по тебе скучали наш малыш!"  -- {PAOLO, rooms/past.moon}
t[367] = "И даже не смей еще раз так пугать нас!"  -- {ANDREA, rooms/past.moon}
t[58] = "А теперь... могу ли я одолжить у вас гитару?"  -- {INES, rooms/past.moon}
t[368] = "Фигня вопрос, сейчас я притащу одну."  -- {PEPPE, rooms/past.moon}
t[369] = "Печально."  -- {PEPPE, rooms/past.moon}
t[370] = "Это навевает меня на мысль по поводу будущей обложки нашего альбома."  -- {PAOLO, rooms/past.moon}
t[59] = "Обязательно включу его, если наш разговор станет интереснее, чем обсуждение \"музыкальной шпаны\"."  -- {INES, rooms/past.moon}
t[60] = "Совсем не похоже на растения дяди Ли."  -- {LOOK, rooms/past.moon}
t[61] = "подозрительное растение"  -- {TEXT, rooms/past.moon}
t[106] = "Никогда не могла б и представить, что кто-то вздумает хранить тут свои перчатки."  -- {LOOK, rooms/common.moon}
t[107] = "шкафчик с перчатками"  -- {TEXT, rooms/common.moon}
t[108] = "Здесь ничего нет."  -- {INES, rooms/common.moon}
t[109] = "Возьму-ка я эту кассету."  -- {INES, rooms/common.moon}
t[110] = "То, что надо."  -- {INES, rooms/common.moon}
t[111] = "Славно, что в этом шкафчике уже много лет никто не лазил."  -- {INES, rooms/common.moon}
t[112] = "Положу-ка я это прямо туда внутрь."  -- {INES, rooms/common.moon}
t[113] = "В этом нет необходимости, я уже это состарила."  -- {INES, rooms/common.moon}
t[114] = "навигатор"  -- {TEXT, inventory.moon}
t[115] = "Это же та самая хроно-катапульта, которая запустила всю эту вакханалию."  -- {LOOK, inventory.moon}
t[116] = "монетка"  -- {TEXT, inventory.moon}
t[117] = "Интересно, найду ли я там шоколад?"  -- {LOOK, inventory.moon}
t[118] = "девайс-раскукоживающий-реальность™"  -- {TEXT, inventory.moon}
t[119] = "КТО, а главное ЗАЧЕМ оставил это прямо тут и прямо в этом горшке? "  -- {LOOK, inventory.moon}
t[120] = "девайс-раскукоживающий-реальность™ (надеюсь, что рабочий)"  -- {TEXT, inventory.moon}
t[121] = "Настроен и готов к использованию."  -- {LOOK, inventory.moon}
t[122] = "Ну конечно же, не может быть все таак просто."  -- {LOOK, inventory.moon}
t[123] = "Давай-ка посмотрим работает ли вообще эта штука."  -- {INES, inventory.moon}
t[633] = "Стоп! Остановись прямо сейчас же!"  -- {PRESIDENT_INES, inventory.moon}
t[124] = "... чего тебе?!"  -- {INES, inventory.moon}
t[125] = "Ты вообще кто такая будешь?"  -- {INES, inventory.moon}
t[634] = "Ладно."  -- {PRESIDENT_INES, inventory.moon}
t[635] = "Главное, не разводи панику. Потому что я - это ты, но из будущего!"  -- {PRESIDENT_INES, inventory.moon}
t[388] = "Привет Инес!"  -- {HOLEEGRAM, inventory.moon}
t[389] = "Ого!"  -- {ANDREA, inventory.moon}
t[126] = "Вот это нифига себе!"  -- {INES, inventory.moon}
t[636] = "У меня нет времени медлить и сюсюкаться с тобой."  -- {PRESIDENT_INES, inventory.moon}
t[637] = "У меня есть супер срочное сообщение для тебя."  -- {PRESIDENT_INES, inventory.moon}
t[638] = "Я - ПРЕЗИДЕНТ."  -- {PRESIDENT_INES, inventory.moon}
t[127] = "Это так важ..."  -- {INES, inventory.moon}
t[639] = "Ты не поняла, что я только что сейчас сказала???"  -- {PRESIDENT_INES, inventory.moon}
t[128] = "Извините, мэм."  -- {INES, inventory.moon}
t[640] = "Я явилась сюда, для того чтобы остановить тебя и предотвратить разрушение пространственно-временного континуума."  -- {PRESIDENT_INES, inventory.moon}
t[641] = "Нажмешь эту кнопку сейчас, и тем самым создашь дыру во времени!"  -- {PRESIDENT_INES, inventory.moon}
t[642] = "Прежде чем использовать девайс, тебе нужно разобраться со всем тем, что может повлиять на создание временных аномалий."  -- {PRESIDENT_INES, inventory.moon}
t[129] = "Скажешь, что я должна сделать для этого?"  -- {INES, inventory.moon}
t[643] = "Мне очень хотелось бы это сделать. Но когда я была в твоей ситуации (прям реально в такой же), то Инес из будущего также не хотела делиться со мной этим секретом."  -- {PRESIDENT_INES, inventory.moon}
t[644] = "В общем, если я расскажу тебе, то это может создать очередную дыру во времени. А нам этого не надо."  -- {PRESIDENT_INES, inventory.moon}
t[130] = "Проклятие."  -- {INES, inventory.moon}
t[645] = "Это именно то, что я говорила в свое время."  -- {PRESIDENT_INES, inventory.moon}
t[646] = "Я вынуждена тебя покинуть."  -- {PRESIDENT_INES, inventory.moon}
t[647] = "Долг зовет."  -- {PRESIDENT_INES, inventory.moon}
t[390] = "Пока Инес!"  -- {HOLEEGRAM, inventory.moon}
t[131] = "девайс-раскукоживающий-реальность™ (сломан)"  -- {TEXT, inventory.moon}
t[132] = "Какой-то дешевый хлам дяди Ли."  -- {LOOK, inventory.moon}
t[133] = "гитарный медиатор"  -- {TEXT, inventory.moon}
t[134] = "Это что? Кровь?"  -- {LOOK, inventory.moon}
t[135] = "кассетный диктофон"  -- {TEXT, inventory.moon}
t[136] = "Внутри него уже есть пленка. Хм, как удобно."  -- {LOOK, inventory.moon}
t[137] = "электрогитара"  -- {TEXT, inventory.moon}
t[138] = "кассетная пленка"  -- {TEXT, inventory.moon}
t[139] = "Очень надеюсь, что это легально."  -- {LOOK, inventory.moon}
t[140] = "старинная кассетная пленка"  -- {TEXT, inventory.moon}
t[141] = "Интересно, а выдержка временем пошла тут на пользу?"  -- {LOOK, inventory.moon}
t[142] = "магнитный звукосниматель"  -- {TEXT, inventory.moon}
t[143] = "Весьма приятно было обзавестись этой находкой."  -- {LOOK, inventory.moon}
t[144] = "Дядя Ли, а ты уверен, что не хочешь пустить меня за руль?"  -- {INES, dialogues/lee.moon}
t[391] = "Всё в порядке моя дорогая Инес! Просто расслабься и наслаждайся видом."  -- {LEE, dialogues/lee.moon}
t[145] = "Мне будет в разы проще это делать, если ты не будешь отвлекаться и внимательно следить за дорогой."  -- {INES, dialogues/lee.moon}
t[392] = "Я видел эту дорогу много много раз и знаю каждый кустик и камешек. Для меня реально там уже нет ничего интересного."  -- {LEE, dialogues/lee.moon}
t[146] = "*Смирившись вздыхает* Ты хотя бы уверен в том, что едешь в правильном направлении?"  -- {INES, dialogues/lee.moon}
t[393] = "Пфф, спрашиваешь! Я могу привезти нас к озеру Фэнфеф хоть с закрытыми глазами!"  -- {LEE, dialogues/lee.moon}
t[147] = "Так то, это не будет сильно отличаться от того, что ты делаешь прямо сейчас."  -- {INES, dialogues/lee.moon}
t[148] = "...разве мы не проезжали этот туннель совсем недавно?"  -- {INES, dialogues/lee.moon}
t[394] = "Эти туннели, они БЕСКОНЕЕЕЧНЫЕ!"  -- {LEE, dialogues/lee.moon}
t[149] = "Дядь Ли."  -- {INES, dialogues/lee.moon}
t[395] = "Ой, блин."  -- {LEE, dialogues/lee.moon}
t[150] = "ДЯДЯ ЛИ."  -- {INES, dialogues/lee.moon}
t[396] = "Похоже я все это время сидел на хроно-катапульте."  -- {LEE, dialogues/lee.moon}
t[397] = "Ааа, точно. Поэтому я никак не мог ее отыскать."  -- {LEE, dialogues/lee.moon}
t[151] = "ХРОНО-КАТАПУЛЬТА!?"  -- {INES, dialogues/lee.moon}
t[398] = "Да, пустяк. Вообще не стоит париться на этот счет."  -- {LEE, dialogues/lee.moon}
t[399] = "Именно для таких неожиданных случаев я как раз таскаю с собой девайс-раскукоживающий-реальность™."  -- {LEE, dialogues/lee.moon}
t[400] = "Ой, кажись он не работает."  -- {LEE, dialogues/lee.moon}
t[152] = "Великолепно."  -- {INES, dialogues/lee.moon}
t[401] = "Где-то рядом точно есть запасной девайс."  -- {LEE, dialogues/lee.moon}
t[402] = "А этот тоже возьми."  -- {LEE, dialogues/lee.moon}
t[153] = "Дядя Ли?"  -- {INES, dialogues/lee.moon}
t[403] = "Да, дорогая?"  -- {LEE, dialogues/lee.moon}
t[154] = "Где мне стоит начать поиски этого устройства?"  -- {ECHO, dialogues/lee.moon}
t[155] = "Для чего нужна эта хроно-катапульта?"  -- {ECHO, dialogues/lee.moon}
t[156] = "Этот фургон выглядит явно крупнее, чем обычно."  -- {ECHO, dialogues/lee.moon}
t[157] = "Хорошо, пока."  -- {ECHO, dialogues/lee.moon}
t[404] = "Пока!"  -- {LEE, dialogues/lee.moon}
t[405] = "Даже и не знаю."  -- {LEE, dialogues/lee.moon}
t[406] = "ТЫ бы на моем месте куда положила?"  -- {LEE, dialogues/lee.moon}
t[158] = "Я!?"  -- {INES, dialogues/lee.moon}
t[159] = "В любом случае это твоих рук дело!"  -- {INES, dialogues/lee.moon}
t[407] = "Предположительно"  -- {LEE, dialogues/lee.moon}
t[408] = "Это мое самое последнее (и величайшее) изобретение!"  -- {LEE, dialogues/lee.moon}
t[409] = "Оно настолько новое, что я даже еще не успел добавить знак ™ к его названию!"  -- {LEE, dialogues/lee.moon}
t[160] = "Что именно оно делает?"  -- {ECHO, dialogues/lee.moon}
t[161] = "Напомни мне, что оно умеет."  -- {ECHO, dialogues/lee.moon}
t[162] = "Зачем ты вообще сделал эту штуковину?"  -- {ECHO, dialogues/lee.moon}
t[163] = "Напомни мне, для каких целей ты это сделал?"  -- {ECHO, dialogues/lee.moon}
t[164] = "Забудь."  -- {ECHO, dialogues/lee.moon}
t[410] = "Какой же дурацкий вопрос!"  -- {LEE, dialogues/lee.moon}
t[411] = "Это девайс для того, чтобы перемещаться во времени."  -- {LEE, dialogues/lee.moon}
t[412] = "Я думаю из его названия можно вполне легко догадаться."  -- {LEE, dialogues/lee.moon}
t[165] = "А разве это все не опасно?"  -- {INES, dialogues/lee.moon}
t[413] = "Конечно же нет! Особенно если ты все делаешь по инструкции."  -- {LEE, dialogues/lee.moon}
t[166] = "А конкретно ТЫ вообще понимаешь, что ты делаешь?"  -- {INES, dialogues/lee.moon}
t[414] = "Нуу, более или менее."  -- {LEE, dialogues/lee.moon}
t[415] = "Это устройство для перемещений во времени."  -- {LEE, dialogues/lee.moon}
t[416] = "Короче, тут в общем я недавно готовлю и вдруг опа! Замечаю, что у меня закончились вилки."  -- {LEE, dialogues/lee.moon}
t[167] = "Дядя Ли, когда же ты уже перестанешь пользоваться одноразовой посудой!"  -- {INES, dialogues/lee.moon}
t[168] = "Ты же так природе вредишь, ну ёмаё!"  -- {INES, dialogues/lee.moon}
t[417] = "Нет, ну конечно все мои вилки они так-то многоразовые."  -- {LEE, dialogues/lee.moon}
t[169] = "Но у тебя они все равно закончились?"  -- {INES, dialogues/lee.moon}
t[418] = "Ага."  -- {LEE, dialogues/lee.moon}
t[419] = "Короче, я пытаюсь сказать, что я вдруг вспомнил, будто у меня точно есть запасные вилки, которые вернувшись я на день ранее мог бы с легкостью обнаружить."  -- {LEE, dialogues/lee.moon}
t[420] = "В общем то, поэтому ко мне пришла гениальная идея создать машину времени, чтобы вернуться назад и прихватить с собой пару вилочек."  -- {LEE, dialogues/lee.moon}
t[421] = "Точно! Видать поэтому они и успешно закончились."  -- {LEE, dialogues/lee.moon}
t[422] = "Потому что я путешествовал в прошлое, чтобы украсть немного вилок."  -- {LEE, dialogues/lee.moon}
t[423] = "У самого себя получается."  -- {LEE, dialogues/lee.moon}
t[170] = "Гениально."  -- {INES, dialogues/lee.moon}
t[424] = "Проектировали его со всей ответственностью, но с пропорциями конечно как-то намудрили."  -- {LEE, dialogues/lee.moon}
t[171] = "...что?"  -- {INES, dialogues/lee.moon}
t[425] = "НО ЭТО ВПОЛНЕ ОЖИДАЕМО, потому что это особенная модель. Ее разрабатывали специально для музыкальных групп 60-х."  -- {LEE, dialogues/lee.moon}
t[172] = "Признавайся, почему ты стал его хозяином?"  -- {INES, dialogues/lee.moon}
t[426] = "В этом мне помог коллекционер."  -- {LEE, dialogues/lee.moon}
t[173] = "Должно быть обошлось тебе это невероятно дорого!"  -- {INES, dialogues/lee.moon}
t[427] = "Дорого?"  -- {LEE, dialogues/lee.moon}
t[174] = "Дядя Ли, ты что украл его что-ли?"  -- {INES, dialogues/lee.moon}
t[428] = "Я его выйграл. Без жульничества и в честной битве!"  -- {LEE, dialogues/lee.moon}
t[429] = "Меня не должно волновать то, что она абсолютно плохо играет в дурака."  -- {LEE, dialogues/lee.moon}
t[430] = "Это специальная модель, которая была выпущена для музыкальных групп 60-х."  -- {LEE, dialogues/lee.moon}
t[431] = "Я достал это у коллекционера."  -- {LEE, dialogues/lee.moon}
t[175] = "Привет."  -- {INES, dialogues/wilson.moon}
t[176] = "Нет ничего стоящего для записи."  -- {INES, dialogues/wilson.moon}
t[177] = "Эти ребята скучные."  -- {INES, dialogues/wilson.moon}
t[178] = "Там."  -- {INES, dialogues/wilson.moon}
t[179] = "Хотелось бы верить, что эта пленка в будущем будет что-то стоить."  -- {INES, dialogues/wilson.moon}
t[432] = "Ребята, вы не поверите тому, что вижу прямо сейчас!"  -- {PAOLO, dialogues/wilson.moon}
t[433] = "Это же та ворчливая деваха с ЗЕЛЕНЫМИ волосами!"  -- {PAOLO, dialogues/wilson.moon}
t[434] = "И кажется, что она явно ЧЕМ-ТО НЕДОВОЛЬНА."  -- {PAOLO, dialogues/wilson.moon}
t[435] = "Да мы все ее видим, балбесина."  -- {ANDREA, dialogues/wilson.moon}
t[436] = "Походу очередная путешественница во времени."  -- {PEPPE, dialogues/wilson.moon}
t[437] = "Ого."  -- {PAOLO, dialogues/wilson.moon}
t[180] = "Вы же ведь группа, да?"  -- {ECHO, dialogues/wilson.moon}
t[438] = "Как ты так догадалась?"  -- {ANDREA, dialogues/wilson.moon}
t[181] = "По гитарам, ага."  -- {ECHO, dialogues/wilson.moon}
t[439] = "А как же \"барабаны\"? Неужели их обошли стороной?"  -- {PAOLO, dialogues/wilson.moon}
t[182] = "Взлохмаченные шевелюры странной конструкции соседствуют с бунтарским настроем."  -- {ECHO, dialogues/wilson.moon}
t[440] = "Смотри-ка кто тут болтает."  -- {PEPPE, dialogues/wilson.moon}
t[183] = "Мое шестое чувство."  -- {ECHO, dialogues/wilson.moon}
t[441] = "Ага, конечно."  -- {ANDREA, dialogues/wilson.moon}
t[184] = "И ваша точка сбора прямо здесь."  -- {ECHO, dialogues/wilson.moon}
t[442] = "Технически это никак не указывает на то, что мы группа."  -- {PEPPE, dialogues/wilson.moon}
t[185] = "Совсем прям не группа?"  -- {INES, dialogues/wilson.moon}
t[443] = "...да."  -- {PEPPE, dialogues/wilson.moon}
t[186] = "На счет вашей группы..."  -- {ECHO, dialogues/wilson.moon}
t[187] = "Я тут кое-что разыскиваю."  -- {ECHO, dialogues/wilson.moon}
t[188] = "Это все."  -- {ECHO, dialogues/wilson.moon}
t[444] = "Бывай."  -- {ANDREA, dialogues/wilson.moon}
t[445] = "Я абсолютно не доверяю тебе, зеленоволосый призрак."  -- {PAOLO, dialogues/wilson.moon}
t[446] = "Не стесняйся, оставайся и обживайся в нашем скромном фургончике."  -- {PEPPE, dialogues/wilson.moon}
t[189] = "Этот фургон, получается, ваша база для репетиций?"  -- {ECHO, dialogues/wilson.moon}
t[447] = "Ага, его так спроектировали и собрали. В том числе и для этих целей."  -- {PAOLO, dialogues/wilson.moon}
t[448] = "А еще мы любим тут поспать."  -- {ANDREA, dialogues/wilson.moon}
t[190] = "Изобретательно."  -- {INES, dialogues/wilson.moon}
t[449] = "Пришлось продать наши дома, чтобы позволить приобрести себе такой крутой фургон."  -- {PEPPE, dialogues/wilson.moon}
t[450] = "И мои барабаны..."  -- {PAOLO, dialogues/wilson.moon}
t[451] = "Разумеется мы совсем ни о чем не сожалеем."  -- {ANDREA, dialogues/wilson.moon}
t[452] = "Лучшее решение в нашей жизни."  -- {PEPPE, dialogues/wilson.moon}
t[191] = "Скучаете же по барабанной установке?"  -- {ECHO, dialogues/wilson.moon}
t[453] = "Да."  -- {PAOLO, dialogues/wilson.moon}
t[192] = "...для вас это проблема?"  -- {INES, dialogues/wilson.moon}
t[454] = "Нет."  -- {PAOLO, dialogues/wilson.moon}
t[193] = "Вы же работаете над какой-то новой песней?"  -- {ECHO, dialogues/wilson.moon}
t[455] = "По сути да, так и есть."  -- {PEPPE, dialogues/wilson.moon}
t[456] = "Над самой лучшей песней, которая у нас есть."  -- {ANDREA, dialogues/wilson.moon}
t[457] = "Давай-ка мы сыграем для тебя если хочешь."  -- {PAOLO, dialogues/wilson.moon}
t[194] = "Мне точно следует записать ее."  -- {INES, dialogues/wilson.moon}
t[195] = "В этом нет необходимости..."  -- {INES, dialogues/wilson.moon}
t[196] = "Это было не так плохо, как я ожидала."  -- {INES, dialogues/wilson.moon}
t[458] = "Во, кстати, это могло бы быть неплохим названием для нашего альбома."  -- {PAOLO, dialogues/wilson.moon}
t[197] = "Ну в общем достаточно о вас, ребята."  -- {ECHO, dialogues/wilson.moon}
t[459] = "Да, мы нарасхват."  -- {PAOLO, dialogues/wilson.moon}
t[460] = "И прежде, чем ты спросишь... "  -- {ANDREA, dialogues/wilson.moon}
t[461] = "...то, что сзади предназначено для личного пользования."  -- {PEPPE, dialogues/wilson.moon}
t[198] = "Чего!?"  -- {INES, dialogues/wilson.moon}
t[199] = "Вообще-то это не то, что я имела ввиду."  -- {INES, dialogues/wilson.moon}
t[200] = "Почему вообще были сделаны такие выводы?"  -- {INES, dialogues/wilson.moon}
t[462] = "Нуу, это то, что обычно хочет этот усатый чувак."  -- {ANDREA, dialogues/wilson.moon}
t[463] = "Хех, умора ходячая."  -- {PAOLO, dialogues/wilson.moon}
t[201] = "...ну разумеется."  -- {INES, dialogues/wilson.moon}
t[202] = "Ребят, у вас же точно где-то припрятано золотишко. Ведь так?"  -- {ECHO, dialogues/wilson.moon}
t[464] = "Ты кстати не первая, кто нас сегодня об этом спрашивает."  -- {PAOLO, dialogues/wilson.moon}
t[465] = "Во-первых это был я."  -- {PEPPE, dialogues/wilson.moon}
t[466] = "А потом уже, я."  -- {ANDREA, dialogues/wilson.moon}
t[467] = "В любом случае, в этой игре вообще нет никакого золота."  -- {PAOLO, dialogues/wilson.moon}
t[203] = "Чеееерт."  -- {INES, dialogues/wilson.moon}
t[204] = "Магниты. Мне просто нужны магниты."  -- {ECHO, dialogues/wilson.moon}
t[205] = "Есть? А если найду?"  -- {INES, dialogues/wilson.moon}
t[468] = "Я так не думаю."  -- {PEPPE, dialogues/wilson.moon}
t[469] = "Сложно поверить, что тебе удастся."  -- {ANDREA, dialogues/wilson.moon}
t[470] = "Это очень маловероятно."  -- {PAOLO, dialogues/wilson.moon}
t[206] = "Да блин."  -- {INES, dialogues/wilson.moon}
t[207] = "Ты РЕАЛЬНО отвечаешь, что у тебя не найдется магнитов для меня?"  -- {ECHO, dialogues/wilson.moon}
t[471] = "Клянусь."  -- {ANDREA, dialogues/wilson.moon}
t[472] = "Нет никого смысла врать тебе."  -- {PEPPE, dialogues/wilson.moon}
t[473] = "Говори за себя."  -- {PAOLO, dialogues/wilson.moon}
t[208] = "Ну, как бы, есть такая информация, что внутри гитар могут быть магнитики."  -- {INES, dialogues/wilson.moon}
t[474] = "Реально в гитарах есть магниты!?"  -- {PAOLO, dialogues/wilson.moon}
t[475] = "Ничего себе!"  -- {ANDREA, dialogues/wilson.moon}
t[476] = "Ого, вот это кстати круто!"  -- {PEPPE, dialogues/wilson.moon}
t[477] = "Тогда получается, что у нас есть нужные тебе магниты."  -- {PEPPE, dialogues/wilson.moon}
t[209] = "Могу ли я одолжить одну из ваших гитар?"  -- {ECHO, dialogues/wilson.moon}
t[478] = "Конечно, почему бы и не..."  -- {PAOLO, dialogues/wilson.moon}
t[479] = "Нет, ни в коем случае!"  -- {ANDREA, dialogues/wilson.moon}
t[480] = "Нам вообще то они нужны так то."  -- {PEPPE, dialogues/wilson.moon}
t[481] = "Ну ты же понимаешь, мы ведь группа и все такое."  -- {ANDREA, dialogues/wilson.moon}
t[210] = "Неужели у вас нет запасных?"  -- {INES, dialogues/wilson.moon}
t[482] = "А знаешь, подумав я начинаю понимать..."  -- {PEPPE, dialogues/wilson.moon}
t[483] = "...что у нас так-то еще есть варианты в заначке."  -- {ANDREA, dialogues/wilson.moon}
t[211] = "Тааак, тогда получается что вы спокойно сможете отдать мне одну? "  -- {INES, dialogues/wilson.moon}
t[484] = "Нет."  -- {PEPPE, dialogues/wilson.moon}
t[212] = "Есть что-нибудь такое, что может убедить вас отдать мне гитару?"  -- {ECHO, dialogues/wilson.moon}
t[485] = "Тоже мимо."  -- {PEPPE, dialogues/wilson.moon}
t[486] = "Вообще без шансов."  -- {ANDREA, dialogues/wilson.moon}
t[487] = "Ребятаа, а что если нам нужен..."  -- {PAOLO, dialogues/wilson.moon}
t[488] = "...МЕДИАТОР?"  -- {PAOLO, dialogues/wilson.moon}
t[489] = "А, точно."  -- {PEPPE, dialogues/wilson.moon}
t[490] = "МЕДИАТОР."  -- {PEPPE, dialogues/wilson.moon}
t[213] = "Медиатор?"  -- {INES, dialogues/wilson.moon}
t[491] = "Когда-то давно у меня был гитарный медиатор."  -- {PEPPE, dialogues/wilson.moon}
t[492] = "Это был самый трушный и верный медиатор в моей жизни."  -- {PEPPE, dialogues/wilson.moon}
t[493] = "Он никогда не осуждал меня и был самым послушным."  -- {PEPPE, dialogues/wilson.moon}
t[494] = "Он даже искренне смеялся над всеми моими шутками и приколами."  -- {PAOLO, dialogues/wilson.moon}
t[495] = "Могу даже уверенно сказать, что он был четвертым участником нашей группы."  -- {ANDREA, dialogues/wilson.moon}
t[496] = "Но как-то раз на одной из репетиций, он просто бесследно пропал."  -- {PAOLO, dialogues/wilson.moon}
t[497] = "Этот день мы никогда не забудем."  -- {PEPPE, dialogues/wilson.moon}
t[498] = "Покойся с миром, наш любимый друг."  -- {ANDREA, dialogues/wilson.moon}
t[214] = "...кажется я начинаю понимать."  -- {INES, dialogues/wilson.moon}
t[215] = "Значит вы дадите мне гитару, если я найду ваш пропавший медиатор?"  -- {ECHO, dialogues/wilson.moon}
t[499] = "Вообще никаких вопросов, если ты и правда сможешь его найти."  -- {PEPPE, dialogues/wilson.moon}
t[216] = "Не бери в голову."  -- {ECHO, dialogues/wilson.moon}
t[500] = "Окей!"  -- {PEPPE, dialogues/wilson.moon}
t[501] = "Он реально ценнее всего, что ты можешь найти в этом фургоне!"  -- {PEPPE, dialogues/wilson.moon}
t[502] = "Хэй!"  -- {ANDREA, dialogues/wilson.moon}
t[503] = "Не, ну он прав."  -- {PAOLO, dialogues/wilson.moon}
t[217] = "Есть идеи, где мне стоит начать свои поиски?"  -- {INES, dialogues/wilson.moon}
t[504] = "Где-то в Вудстоке, я полагаю."  -- {PEPPE, dialogues/wilson.moon}
t[218] = "Ну разумеется."  -- {INES, dialogues/wilson.moon}
t[219] = "Коллекционируете ли вы кожаные куртки?"  -- {ECHO, dialogues/collector.moon}
t[220] = "Коллекционируете ли вы золотые барометры?"  -- {ECHO, dialogues/collector.moon}
t[221] = "Коллекционируете ли вы средневековые орудия пыток?"  -- {ECHO, dialogues/collector.moon}
t[222] = "Коллекционируете ли вы овощи странной формы?"  -- {ECHO, dialogues/collector.moon}
t[223] = "Коллекционируете ли вы тревожную поэзию подростков?"  -- {ECHO, dialogues/collector.moon}
t[224] = "Коллекционируете ли вы миниатюры морепродуктов?"  -- {ECHO, dialogues/collector.moon}
t[225] = "Коллекционируете ли вы сериалы начала 2000-х?"  -- {ECHO, dialogues/collector.moon}
t[226] = "Коллекционируете ли вы дешевые журналы пятидесятых годов?"  -- {ECHO, dialogues/collector.moon}
t[227] = "Коллекционируете ли вы мои ранние школьные фото?"  -- {ECHO, dialogues/collector.moon}
t[228] = "Тьфу."  -- {INES, dialogues/collector.moon}
t[229] = "Коллекционируете ли вы спортивные альманахи?"  -- {ECHO, dialogues/collector.moon}
t[230] = "Коллекционируете ли вы пачки чипсов с призами внутри?"  -- {ECHO, dialogues/collector.moon}
t[231] = "Коллекционируете ли вы неприличные брелки?"  -- {ECHO, dialogues/collector.moon}
t[232] = "Коллекционируете ли вы приличные брелки?"  -- {ECHO, dialogues/collector.moon}
t[233] = "Коллекционируете ли вы супер переоцененную музыку?"  -- {ECHO, dialogues/collector.moon}
t[234] = "Коллекционируете ли вы не сохранившиеся до наших дней мечи?"  -- {ECHO, dialogues/collector.moon}
t[235] = "Коллекционируете ли вы коллекционеров?"  -- {ECHO, dialogues/collector.moon}
t[236] = "Привет."  -- {INES, dialogues/collector.moon}
t[505] = "Ты все еще здесь."  -- {COLLECTOR, dialogues/collector.moon}
t[506] = "ТЫ ВООБЩЕ КТО!?"  -- {COLLECTOR, dialogues/collector.moon}
t[237] = "...ну типо, путешественник во времени?"  -- {INES, dialogues/collector.moon}
t[507] = "О нет, неужели ты пришла от того стремного чувака с усами?"  -- {COLLECTOR, dialogues/collector.moon}
t[238] = "Эй на минуточку, только Я могу называть своего дядюшку Ли \"стремным\"."  -- {INES, dialogues/collector.moon}
t[508] = "Ок, мне все равно."  -- {COLLECTOR, dialogues/collector.moon}
t[509] = "Уходи."  -- {COLLECTOR, dialogues/collector.moon}
t[510] = "СЕЙЧАС."  -- {COLLECTOR, dialogues/collector.moon}
t[511] = "Или хотя бы постарайся ничего тут не трогать."  -- {COLLECTOR, dialogues/collector.moon}
t[239] = "Фургон выглядит как-то по-другому."  -- {ECHO, dialogues/collector.moon}
t[240] = "Что это за вообще тут хлам?"  -- {INES, dialogues/collector.moon}
t[512] = "Хлам?"  -- {COLLECTOR, dialogues/collector.moon}
t[513] = "ХЛАМ!?"  -- {COLLECTOR, dialogues/collector.moon}
t[514] = "Всё это - коллекция высочайшего класса!"  -- {COLLECTOR, dialogues/collector.moon}
t[515] = "Тебе этого просто не понять."  -- {COLLECTOR, dialogues/collector.moon}
t[241] = "А вы типо коллекционер?"  -- {INES, dialogues/collector.moon}
t[516] = "Не типо, а самый НАСТОЯЩИЙ коллекционер."  -- {COLLECTOR, dialogues/collector.moon}
t[242] = "И что за барахло вы любите коллекционировать?"  -- {ECHO, dialogues/collector.moon}
t[517] = "Пожалуйста, воздержись называть эти бесценные артефакты *барахлом*."  -- {COLLECTOR, dialogues/collector.moon}
t[518] = "Мой особый интерес заключается в коллекционировании предметов, которые прямо или косвенно связанны с МУЗЫКАЛЬНЫМИ группами."  -- {COLLECTOR, dialogues/collector.moon}
t[519] = "У меня есть всякие постеры, мини-альбомы, пластинки и копии дисков (которые я сделала сама)..."  -- {COLLECTOR, dialogues/collector.moon}
t[520] = "...даже все эти стены вокруг когда-то принадлежали одной МУЗЫКАЛЬНОЙ группе."  -- {COLLECTOR, dialogues/collector.moon}
t[243] = "Вы имеете ввиду фургон этот что-ли?"  -- {INES, dialogues/collector.moon}
t[521] = "Это по истине абсолютно ультимативная коллекция."  -- {COLLECTOR, dialogues/collector.moon}
t[522] = "...или она бы могла такой быть, если б только..."  -- {COLLECTOR, dialogues/collector.moon}
t[244] = "Ладно. Я ухожу."  -- {ECHO, dialogues/collector.moon}
t[523] = "Чудно."  -- {COLLECTOR, dialogues/collector.moon}
t[245] = "Есть ли у вас медиатор, который в свое время потеряла одна известная музыкальная группа?"  -- {ECHO, dialogues/collector.moon}
t[524] = "Который из?"  -- {COLLECTOR, dialogues/collector.moon}
t[525] = "Ты вообще можешь представить себе сколько медиаторов теряет одна группа в течении всей своей карьеры?"  -- {COLLECTOR, dialogues/collector.moon}
t[526] = "У меня их сотни!"  -- {COLLECTOR, dialogues/collector.moon}
t[246] = "И... даже тот самый особенный?"  -- {INES, dialogues/collector.moon}
t[527] = "Они ВСЕ особенные!"  -- {COLLECTOR, dialogues/collector.moon}
t[528] = "Ведь ими же играли настоящие МУЗЫКАНТЫ!"  -- {COLLECTOR, dialogues/collector.moon}
t[247] = "...мдаа"  -- {INES, dialogues/collector.moon}
t[248] = "Есть ли то, чего вам не хватает в вашей коллекции?"  -- {ECHO, dialogues/collector.moon}
t[529] = "Легенды гласят, что есть такая ГРУППА, которая написала самую умопомрачительную песню в истории."  -- {COLLECTOR, dialogues/collector.moon}
t[530] = "Эта песня настолько мощная, что птицы пролетающие мимо начинают непроизвольно подпевать."  -- {COLLECTOR, dialogues/collector.moon}
t[531] = "Но к моему глубокому сожалению эта песня была утеряна."  -- {COLLECTOR, dialogues/collector.moon}
t[532] = "Хотя ходит куча слухов, что песню все-таки успели записать."  -- {COLLECTOR, dialogues/collector.moon}
t[533] = "ДЕМО ПЛЕНКА!!!"  -- {COLLECTOR, dialogues/collector.moon}
t[534] = "...мне очень очень хотелось бы это заполучить."  -- {COLLECTOR, dialogues/collector.moon}
t[249] = "Понятное дело."  -- {INES, dialogues/collector.moon}
t[250] = "Коллекционируете ли вы может быть что-то из золота?"  -- {ECHO, dialogues/collector.moon}
t[535] = "Нет, в этой игре нет и не будет какого-либо золота."  -- {COLLECTOR, dialogues/collector.moon}
t[251] = "Ну блин, опять."  -- {INES, dialogues/collector.moon}
t[252] = "Коллекционируете ли вы может какие-нибудь магниты?"  -- {ECHO, dialogues/collector.moon}
t[536] = "Кто вообще в здравом уме будет коллекционировать магниты?"  -- {COLLECTOR, dialogues/collector.moon}
t[253] = "...дядя Ли."  -- {INES, dialogues/collector.moon}
t[254] = "Коллекционируете ли вы может быть что-то, что СОСТОИТ из магнитов?"  -- {INES, dialogues/collector.moon}
t[537] = "Гитары, я полагаю в них есть магниты."  -- {COLLECTOR, dialogues/collector.moon}
t[255] = "В гитарах могут быть магниты!?"  -- {INES, dialogues/collector.moon}
t[538] = "Ну конечно, это же все знают."  -- {COLLECTOR, dialogues/collector.moon}
t[256] = "Крутяк!"  -- {INES, dialogues/collector.moon}
t[257] = "...нооо, я не вижу здесь никаких гитар."  -- {INES, dialogues/collector.moon}
t[539] = "Конечно, они ведь в хранилище."  -- {COLLECTOR, dialogues/collector.moon}
t[540] = "Это же передвижная коллекция. "  -- {COLLECTOR, dialogues/collector.moon}
t[258] = "Черт."  -- {INES, dialogues/collector.moon}
t[541] = "Поверь мне, в гитарах реально есть магниты."  -- {COLLECTOR, dialogues/collector.moon}
t[542] = "Но моих гитар к сожалению тут нет."  -- {COLLECTOR, dialogues/collector.moon}
t[543] = "Нет."  -- {COLLECTOR, dialogues/collector.moon}
t[259] = "Скучно."  -- {ECHO, dialogues/collector.moon}
t[260] = "Я вернулась."  -- {INES, dialogues/holeegram.moon}
t[544] = "Помести девайс прямо подо мной, чтоб я мог его проанализировать."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[261] = "...дядь Ли?"  -- {INES, dialogues/holeegram.moon}
t[545] = "Молодая Инес! Кажется будто я не видел тебя целую вечность!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[262] = "...что с тобой произошло?"  -- {INES, dialogues/holeegram.moon}
t[546] = "Я ХУЛИГРАААМА!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[263] = "Ну разумеется."  -- {INES, dialogues/holeegram.moon}
t[264] = "Но почему? С тобой что-то приключилось?"  -- {INES, dialogues/holeegram.moon}
t[547] = "Все тип-топ, мне просто захотелось попробовать что-нибудь новенькое."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[548] = "Я не чувствовал себя так легко с тех пор, как мне было 105!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[549] = "Но, что мы все обо мне да обо мне."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[550] = "Я так полагаю ты оказалась тут с помощью моей чудотворной хроно-катапульты™."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[265] = "Я бы не осмеливалась называть ее \"чудотворной\"..."  -- {NOECHO, dialogues/holeegram.moon}
t[266] = "Ты большой счастливчик, что я не могу отвесить тебе смачного пинка."  -- {NOECHO, dialogues/holeegram.moon}
t[267] = "Я здесь, потому что ты буквально ЧЕРЕЗ ЖОПУ активировал машину времени."  -- {NOECHO, dialogues/holeegram.moon}
t[268] = "...ага"  -- {INES, dialogues/holeegram.moon}
t[269] = "Насколько в далеком будущем мы оказались?"  -- {ECHO, dialogues/holeegram.moon}
t[551] = "На сотни лет вперед!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[270] = "Поможешь мне выбраться из этого временного тунеля?"  -- {ECHO, dialogues/holeegram.moon}
t[552] = "Временной тунель?"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[271] = "Ты нажал на свою прикольную кнопочку, исчез и оставил меня в неприятном положении."  -- {INES, dialogues/holeegram.moon}
t[272] = "Тебе это о чем-нибудь говорит?"  -- {INES, dialogues/holeegram.moon}
t[553] = "О дорогая."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[554] = "Тебе нужно быть немного конкретнее со мной в этом плане."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[555] = "Я как минимум припоминаю пять подобных случаев."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[273] = "Великолепно."  -- {INES, dialogues/holeegram.moon}
t[274] = "Скорее всего это должен быть самый первый случай из этих пяти."  -- {INES, dialogues/holeegram.moon}
t[556] = "Ах точно, наше путешествие до озера Фэнфеф!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[275] = "Верно."  -- {INES, dialogues/holeegram.moon}
t[557] = "Значит нам нужно починить твой девайс-раскукоживающий-реальность™, верно?"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[276] = "Понятия не имею, скажи-ка ТЫ мне это."  -- {INES, dialogues/holeegram.moon}
t[558] = "Нам определенно точно нужно починить твой девайс-раскукоживающий-реальность™."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[277] = "Каким образом ты будешь приводить его в рабочее состояние?"  -- {ECHO, dialogues/holeegram.moon}
t[559] = "В общем мне нужен МАГНИТ и МОНЕТКА из музея."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[278] = "Принято."  -- {INES, dialogues/holeegram.moon}
t[279] = "Это и правда иронично, что мы должны чинить этот девайс."  -- {ECHO, dialogues/holeegram.moon}
t[560] = "Знаю."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[561] = "Если конечно я не потерял свой девайс-чинящий-девайс-раскукоживающий-реальность™."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[280] = "А что если девайс-чинящий-девайс-раскукоживающий-реальность™ вдруг тоже сломается? Как ты будешь приводить его в чувство?"  -- {ECHO, dialogues/holeegram.moon}
t[562] = "Все очень просто. Конечно же с помощью девайса-чинящего-девайс-чинящий-девайс-раскукоживающий-реальность™."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[563] = "Его я кстати уже создал на всякий случай."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[281] = "Господи, дядя. Ты и правда очень странный!"  -- {INES, dialogues/holeegram.moon}
t[282] = "У тебя вообще есть какие-то идеи, как устранить аномалию, которая мешает мне пользоваться устройством?"  -- {ECHO, dialogues/holeegram.moon}
t[564] = "Конечно, я ведь как раз очень хорошо разбираюсь в этих аномалиях!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[565] = "Если память мне не изменяет, то я сделал только одно подобное устройство."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[283] = "Но я прекрасно помню, что у меня их было сразу два."  -- {INES, dialogues/holeegram.moon}
t[566] = "Ааа, тогда аномалия скорее всего вызвана как раз таки этим фактом."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[284] = "...хммм"  -- {INES, dialogues/holeegram.moon}
t[285] = "Хорошо, увидимся позже!"  -- {ECHO, dialogues/holeegram.moon}
t[567] = "Или даже раньше!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[286] = "Что произошло со мной в этой временной линии?"  -- {ECHO, dialogues/holeegram.moon}
t[568] = "Ты стала президентом!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[287] = "Невероятно!"  -- {INES, dialogues/holeegram.moon}
t[288] = "Подожди, президентом чего?"  -- {INES, dialogues/holeegram.moon}
t[569] = "Да. Ты являешься президентом Ч.Е.Г.О."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[289] = "Ладно неважно, просто помоги мне выбраться из этой западни."  -- {INES, dialogues/holeegram.moon}
t[290] = "Что случилось с твоим телом?"  -- {ECHO, dialogues/holeegram.moon}
t[570] = "Ну..."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[571] = "Я честно говоря сам до сих пор не особо понимаю."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[572] = "Я как бы засунул его туда куда не надо."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[291] = "Чего?!"  -- {INES, dialogues/holeegram.moon}
t[573] = "Ах, не стоит беспокоиться дорогая."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[574] = "Президент Инес уже занимается этим делом, и я уверен, что она совсем скоро найдет его."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[575] = "Инес из будущего уже занимается этим делом, и я уверен, что она совсем скоро найдет его."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[292] = "Чем больше я узнаю про это время, тем меньше я хочу в него погружаться."  -- {INES, dialogues/holeegram.moon}
t[293] = "Что случилось с фургоном?"  -- {ECHO, dialogues/holeegram.moon}
t[576] = "Теперь это \"Музей Дядюшки Ли\"."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[294] = "Выходит так, что ты теперь стал популярным?"  -- {INES, dialogues/holeegram.moon}
t[577] = "Нуууу, нет."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[578] = "Я единственный, кто приложил руку к созданию этого музея."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[295] = "Конечно, никто и не спорит."  -- {INES, dialogues/holeegram.moon}
t[296] = "Забудь."  -- {ECHO, dialogues/holeegram.moon}
t[579] = "Мне нужно несколько секунд."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[580] = "Это устаревшая модель."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[581] = "Результаты уже готовы!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[582] = "Нам крупно повезло!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[583] = "Все очень просто."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[584] = "Все что нам нужно это:"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[585] = "Сильный МАГНИТ..."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[586] = "...и та МОНЕТКА в задней части музея."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[297] = "Где я могу найти магнит?"  -- {ECHO, dialogues/holeegram.moon}
t[298] = "Могу себе представить, что в будущем их явно должно быть в избытке."  -- {INES, dialogues/holeegram.moon}
t[587] = "Эммм, ну как бы нет."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[588] = "С тех пор, как произошел несчастный случай."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[299] = "...ОКЕЙ."  -- {INES, dialogues/holeegram.moon}
t[300] = "В других временных линиях это так и есть."  -- {INES, dialogues/holeegram.moon}
t[301] = "Монетка выглядит очень подозрительно."  -- {ECHO, dialogues/holeegram.moon}
t[589] = "Нууу, ТЕХНИЧЕСКИ мне просто нужно немного золота."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[590] = "Я просто очень хотел тебе помочь."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[302] = "Но я никак не могу туда добраться!"  -- {INES, dialogues/holeegram.moon}
t[303] = "Разве я не могу просто поискать какую-нибудь другую золотую штукенцию?"  -- {INES, dialogues/holeegram.moon}
t[591] = "Нет, в этой игре больше нет никакого золота."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[592] = "Прости."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[304] = "Печально."  -- {INES, dialogues/holeegram.moon}
t[305] = "Спасибо, понятно."  -- {ECHO, dialogues/holeegram.moon}
t[306] = "Шестидесятые."  -- {NOECHO, dialogues/navigator.moon}
t[307] = "Девяностые."  -- {NOECHO, dialogues/navigator.moon}
t[308] = "Настоящее."  -- {NOECHO, dialogues/navigator.moon}
t[309] = "БУДУЩЕЕ."  -- {NOECHO, dialogues/navigator.moon}
t[310] = "Оставайся здесь."  -- {NOECHO, dialogues/navigator.moon}
t[316] = "Все окончено?"  -- {INES, dialogues/ending.moon}
t[317] = "Это же ведь правильное время?"  -- {INES, dialogues/ending.moon}
t[593] = "Инес, дорогая!"  -- {LEE, dialogues/ending.moon}
t[594] = "У тебя получилось!"  -- {LEE, dialogues/ending.moon}
t[595] = "Почему тебя так долго не было?"  -- {LEE, dialogues/ending.moon}
t[318] = "ПОПРОБУЙ УГАДАЙ ПОЧЕМУ МЕНЯ ТАК ДОЛГО НЕ БЫЛО!?"  -- {INES, dialogues/ending.moon}
t[319] = "ТЫ БРОСИЛ И ОСТАВИЛ МЕНЯ ВО ВРЕМЕННОМ ТУННЕЛЕ!"  -- {INES, dialogues/ending.moon}
t[596] = "Что, прям вот так?"  -- {LEE, dialogues/ending.moon}
t[320] = "Твоя дурацкая кнопка сработала только в твою сторону!"  -- {INES, dialogues/ending.moon}
t[597] = "Ах да, я уже и забыл про это."  -- {LEE, dialogues/ending.moon}
t[598] = "Ну, похоже ты в порядке. И добралась в итоге целой и невредимой."  -- {LEE, dialogues/ending.moon}
t[599] = "Ты всегда была очень находчивой и изобретательной."  -- {LEE, dialogues/ending.moon}
t[321] = "*Недовольно ворчит*"  -- {INES, dialogues/ending.moon}
t[600] = "Ты ведь ничего не изменила в прошлом, ведь так?"  -- {LEE, dialogues/ending.moon}
t[322] = "Эммм..."  -- {INES, dialogues/ending.moon}
t[323] = "А что ты имеешь ввиду под словом \"изменила\"?"  -- {INES, dialogues/ending.moon}
t[601] = "О боже."  -- {LEE, dialogues/ending.moon}
t[602] = "Возможно, тебе стоит пройти немного вперед."  -- {LEE, dialogues/ending.moon}
t[603] = "Что здесь происходит, а?"  -- {COLLECTOR, dialogues/ending.moon}
t[324] = "Оооо, нет."  -- {INES, dialogues/ending.moon}
t[604] = "Куда подевалась моя коллекция!?"  -- {COLLECTOR, dialogues/ending.moon}
t[605] = "Ого!"  -- {PAOLO, dialogues/ending.moon}
t[606] = "О."  -- {COLLECTOR, dialogues/ending.moon}
t[607] = "Мой."  -- {COLLECTOR, dialogues/ending.moon}
t[608] = "Бог."  -- {COLLECTOR, dialogues/ending.moon}
t[609] = "Это...?"  -- {COLLECTOR, dialogues/ending.moon}
t[610] = "Ребята, посмотрите на эти глаза!"  -- {ANDREA, dialogues/ending.moon}
t[611] = "Я твердо уверен, что она наш..."  -- {PAOLO, dialogues/ending.moon}
t[612] = "...ФАНАААТ!"  -- {PAOLO, dialogues/ending.moon}
t[613] = "Кстати вы заметили, что все наши фанаты какие-то немного угрюмые и ворчливые?"  -- {PEPPE, dialogues/ending.moon}
t[325] = "Эй, я не ваша фанатка!"  -- {INES, dialogues/ending.moon}
t[614] = "И кстати, я совсем не ворчливая! Ишь вздумали тут сразу ярлыки вешать."  -- {LEE, dialogues/ending.moon}
t[615] = "ЭТО ЖЕ ТА САМАЯ ГРУПААААА!"  -- {COLLECTOR, dialogues/ending.moon}
t[326] = "Что я только что сделала."  -- {INES, dialogues/ending.moon}
t[616] = "КТО ЖЕЛАЕТ ОТПРАВИТЬСЯ В ПУТЕШЕСТВИЕ ДО ОЗЕРА ФЭНФЕФ?"  -- {LEE, dialogues/ending.moon}
t[617] = "Я! Я! Я!"  -- {PEPPE, dialogues/ending.moon}
t[618] = "Какое там озеро? ФЭФ? ФЭФЭФ?"  -- {ANDREA, dialogues/ending.moon}
t[619] = "Дорожное путешествие! Дааааа!"  -- {PAOLO, dialogues/ending.moon}
t[620] = "Ну а я пойду туда, куда пойдут и они."  -- {COLLECTOR, dialogues/ending.moon}
t[327] = "Разве нам не нужно постараться вернуть их назад в их временные линии?"  -- {INES, dialogues/ending.moon}
t[621] = "Нее, мы еще успеем это сделать."  -- {LEE, dialogues/ending.moon}
t[622] = "Для этого у нас еще вся жизнь впереди."  -- {LEE, dialogues/ending.moon}
t[623] = "Ну, ты в общем то смогла уяснить что-нибудь новое из всей этой ситуации, которая приключилась с тобой?"  -- {LEE, dialogues/ending.moon}
t[328] = "Никогда не доверяй до конца своим девайсам."  -- {ECHO, dialogues/ending.moon}
t[624] = "Ты постоянно твердишь про это."  -- {LEE, dialogues/ending.moon}
t[329] = "В будущем, ты кстати еще более стремный."  -- {ECHO, dialogues/ending.moon}
t[625] = "Надеюсь на это, я тренируюсь каждый день."  -- {LEE, dialogues/ending.moon}
t[330] = "Мне срочно нужно баллотироваться в президенты."  -- {ECHO, dialogues/ending.moon}
t[626] = "\"Президент Инес\"."  -- {LEE, dialogues/ending.moon}
t[627] = "Во, а звучит то как круто."  -- {LEE, dialogues/ending.moon}
t[331] = "В игры с моделью \"плати сколько хочешь\" не стоит играть бесплатно."  -- {ECHO, dialogues/ending.moon}
t[628] = "Мудрые слова."  -- {LEE, dialogues/ending.moon}
t[629] = "ОКЕЙ ДЕТИШКИ!"  -- {LEE, dialogues/ending.moon}
t[630] = "ДАВАЙТЕ-КА СПОЕМ ПАРОЧКУ ТУРИСТИЧЕСКИХ ПЕСЕН!"  -- {LEE, dialogues/ending.moon}
t[631] = "Мы с радостью сыграем!"  -- {PAOLO, dialogues/ending.moon}
t[632] = "ДААААА!!!"  -- {COLLECTOR, dialogues/ending.moon}
t[332] = "...это будет по-настоящему долгая поездка."  -- {INES, dialogues/ending.moon}
t[333] = "Вернуться в игру"  -- {TEXT, gui/options.moon}
t[335] = "Громкость музыки"  -- {TEXT, gui/options.moon}
t[649] = "Полноэкранный режим"  -- {TEXT, gui/options.moon}
t[650] = "Пропуск диалогов левой кнопкой мыши"  -- {TEXT, gui/options.moon}
t[651] = "Пропуск диалогов правой кнопкой мыши"  -- {TEXT, gui/options.moon}
t[344] = "Начать игру"  -- {TEXT, gui/start.moon}
t[345] = "Настройки"  -- {TEXT, gui/start.moon}
t[652] = "<Русский>"  -- {TEXT, gui/start.moon}
t[346] = "Текст, графика и анимация: Andrea Cerbone"  -- {TEXT, credits.moon}
t[347] = "Текст, музыка: Paolo Cotrone"  -- {TEXT, credits.moon}
t[348] = "Текст, код, дополнительная графика и звуки, дизайн шрифта: Giuseppe Sellaroli"  -- {TEXT, credits.moon}
t[653] = "Шрифт: LanaPixel"  -- {TEXT, credits.moon}
t[352] = "Игра была предоставлена для участников LocJAM 6 (2024)"  -- {TEXT, credits.moon}
t[354] = "Автор русской локализации: Artur Somov"  -- {TEXT, credits.moon}
t[356] = "Спасибо, что поиграли и оценили мою локализацию! Всем удачи и всех благ!"  -- {TEXT, credits.moon}

return t
